CALL PRC_ADM_PLUVIOMETRO(NULL);
/
DECLARE
  CURSOR cr_data IS SELECT ROWID FROM DDN_PLUVIOMETRO WHERE CD_EQUIPAMENTO in (:equipamentos) AND TO_DATE(DT_HR_LOCAL, 'DD/MM/YYYY HH24:MI:SS') >= TO_DATE(:data_inicio, 'YYYY-MM-DD HH24:MI:SS');
  TYPE t_data IS TABLE OF cr_data%ROWTYPE INDEX BY BINARY_INTEGER;
  r_data t_data;
BEGIN
  OPEN cr_data;
  LOOP FETCH cr_data
    BULK COLLECT INTO r_data
    LIMIT 1000;
    EXIT WHEN r_data.COUNT = 0;
    FORALL I IN 1..r_data.COUNT
      DELETE FROM DDN_PLUVIOMETRO WHERE ROWID = r_data(I).ROWID;
    COMMIT;
  END LOOP;
  CLOSE cr_data;
END;
/
DECLARE
  CURSOR cr_data IS SELECT ROWID FROM DDN_METEOROLOGIA WHERE CD_EQUIPAMENTO in (:equipamentos) AND DT_HR_LOCAL >= TO_DATE(:data_inicio, 'YYYY-MM-DD HH24:MI:SS');
  TYPE t_data IS TABLE OF cr_data%ROWTYPE INDEX BY BINARY_INTEGER;
  r_data t_data;
BEGIN
  OPEN cr_data;
  LOOP FETCH cr_data
    BULK COLLECT INTO r_data
    LIMIT 1000;
    EXIT WHEN r_data.COUNT = 0;
    FORALL I IN 1..r_data.COUNT
      DELETE FROM DDN_METEOROLOGIA WHERE ROWID = r_data(I).ROWID;
    COMMIT;
  END LOOP;
  CLOSE cr_data;
END;
/
DECLARE
  CURSOR cr_data IS SELECT ROWID FROM DDN_METEOROLOGIA_BKP WHERE CD_EQUIPAMENTO in (:equipamentos) AND DT_HR_LOCAL >= TO_DATE(:data_inicio, 'YYYY-MM-DD HH24:MI:SS');
  TYPE t_data IS TABLE OF cr_data%ROWTYPE INDEX BY BINARY_INTEGER;
  r_data t_data;
BEGIN
  OPEN cr_data;
  LOOP FETCH cr_data
    BULK COLLECT INTO r_data
    LIMIT 1000;
    EXIT WHEN r_data.COUNT = 0;
    FORALL I IN 1..r_data.COUNT
      DELETE FROM DDN_METEOROLOGIA_BKP WHERE ROWID = r_data(I).ROWID;
    COMMIT;
  END LOOP;
  CLOSE cr_data;
END;
/
DECLARE
  CURSOR cr_data IS SELECT ROWID FROM DDN_METEOROLOGIA_RESUMIDA WHERE CD_EQUIPAMENTO in (:equipamentos) AND DT_HR_LOCAL >= TO_DATE(:data_inicio, 'YYYY-MM-DD HH24:MI:SS');
  TYPE t_data IS TABLE OF cr_data%ROWTYPE INDEX BY BINARY_INTEGER;
  r_data t_data;
BEGIN
  OPEN cr_data;
  LOOP FETCH cr_data
    BULK COLLECT INTO r_data
    LIMIT 1000;
    EXIT WHEN r_data.COUNT = 0;
    FORALL I IN 1..r_data.COUNT
      DELETE FROM DDN_METEOROLOGIA_RESUMIDA WHERE ROWID = r_data(I).ROWID;
    COMMIT;
  END LOOP;
  CLOSE cr_data;
END;
/
DECLARE
  CURSOR cr_data IS SELECT ROWID FROM DDN_METEOROLOGIA_RESUMIDA_BKP WHERE CD_EQUIPAMENTO in (:equipamentos) AND DT_HR_LOCAL >= TO_DATE(:data_inicio, 'YYYY-MM-DD HH24:MI:SS');
  TYPE t_data IS TABLE OF cr_data%ROWTYPE INDEX BY BINARY_INTEGER;
  r_data t_data;
BEGIN
  OPEN cr_data;
  LOOP FETCH cr_data
    BULK COLLECT INTO r_data
    LIMIT 1000;
    EXIT WHEN r_data.COUNT = 0;
    FORALL I IN 1..r_data.COUNT
      DELETE FROM DDN_METEOROLOGIA_RESUMIDA_BKP WHERE ROWID = r_data(I).ROWID;
    COMMIT;
  END LOOP;
  CLOSE cr_data;
END;
/
DECLARE
  CURSOR cr_data IS SELECT ROWID FROM TMP_MONITORAMENTO_ALERTA WHERE CD_EQUIPAMENTO in (:equipamentos) AND DT_HR_LOCAL >= TO_DATE(:data_inicio, 'YYYY-MM-DD HH24:MI:SS');
  TYPE t_data IS TABLE OF cr_data%ROWTYPE INDEX BY BINARY_INTEGER;
  r_data t_data;
BEGIN
  OPEN cr_data;
  LOOP FETCH cr_data
    BULK COLLECT INTO r_data
    LIMIT 1000;
    EXIT WHEN r_data.COUNT = 0;
    FORALL I IN 1..r_data.COUNT
      DELETE FROM TMP_MONITORAMENTO_ALERTA WHERE ROWID = r_data(I).ROWID;
    COMMIT;
  END LOOP;
  CLOSE cr_data;
END;
/
DECLARE
  CURSOR cr_data IS SELECT ROWID FROM LOG_ERRO_PLUVIOMETRO WHERE CD_EQUIPAMENTO in (:equipamentos) AND DT_HR_LOCAL >= TO_DATE(:data_inicio, 'YYYY-MM-DD HH24:MI:SS');
  TYPE t_data IS TABLE OF cr_data%ROWTYPE INDEX BY BINARY_INTEGER;
  r_data t_data;
BEGIN
  OPEN cr_data;
  LOOP FETCH cr_data
    BULK COLLECT INTO r_data
    LIMIT 1000;
    EXIT WHEN r_data.COUNT = 0;
    FORALL I IN 1..r_data.COUNT
      DELETE FROM LOG_ERRO_PLUVIOMETRO WHERE ROWID = r_data(I).ROWID;
    COMMIT;
  END LOOP;
  CLOSE cr_data;
END;
/
INSERT INTO TMP_PLUVIOMETRO
( CD_ID
, FG_TP_REGISTRO
, CD_EQUIPAMENTO
, FG_TP_EQUIPAMENTO
, FG_TP_COMUNICACAO
, CD_VERSAO_FIRMWARE
, DT_HR_UTC
, DT_HR_LOCAL
, DT_HR_SERVIDOR
, DT_HR_SERVIDOR_DMZ
, VL_LATITUDE
, VL_LONGITUDE
, CD_FAZENDA
, CD_ZONA
, CD_TALHAO
, VL_ALARME
, VL_FOLHA_MOLHADA
, VL_UMIDADE_SOLO
, VL_RSSI
, VL_SNR
, VL_BATERIA
, VL_FRAME_ID
, VL_CONTADOR_CHUVA
, VL_UMIDADE_SOLO_2
, FG_PROCESSADO
, VL_DIRECAO_VENTO
, VL_VEL_VENTO
, VL_VEL_VENTO_PICO
, VL_TEMPERATURA
, VL_UMIDADE
, VL_RADIACAO_SOLAR
, VL_PONTO_ORVALHO
, VL_PRESSAO_ATMOSFERICA
, VL_UMIDADE_SOLO_3
, CD_ESTADO)
  SELECT CD_ID
    , FG_TP_REGISTRO
    , CD_EQUIPAMENTO
    , FG_TP_EQUIPAMENTO
    , FG_TP_COMUNICACAO
    , CD_VERSAO_FIRMWARE
    , DT_HR_UTC
    , DT_HR_LOCAL
    , DT_HR_SERVIDOR
    , DT_HR_SERVIDOR_DMZ
    , VL_LATITUDE
    , VL_LONGITUDE
    , CD_FAZENDA
    , CD_ZONA
    , CD_TALHAO
    , VL_ALARME
    , VL_FOLHA_MOLHADA
    , VL_UMIDADE_SOLO
    , VL_RSSI
    , VL_SNR
    , VL_BATERIA
    , VL_FRAME_ID
    , VL_CONTADOR_CHUVA
    , VL_UMIDADE_SOLO_2
    , 'F'
    , VL_DIRECAO_VENTO
    , VL_VEL_VENTO
    , VL_VEL_VENTO_PICO
    , VL_TEMPERATURA
    , VL_UMIDADE
    , VL_RADIACAO_SOLAR
    , VL_PONTO_ORVALHO
    , VL_PRESSAO_ATMOSFERICA
    , VL_UMIDADE_SOLO_3
    , CD_ESTADO
    FROM DDP_PLUVIOMETRO
    WHERE CD_EQUIPAMENTO in (:equipamentos)
      AND DT_HR_LOCAL >= TO_DATE(:data_inicio, 'YYYY-MM-DD HH24:MI:SS');
/
DELETE FROM CFG_CONTROLE_PLUVIOMETRO WHERE CD_EQUIPAMENTO in (:equipamentos);
/
COMMIT;